### ISSUE TITLE
Factor 0.1

### ISSUE THREAD

**Issue by MartinLiebig** [waymanglover/hearthstats#1]
Hi All,

in get_deck_metainfo is the line

`count = int(pagecount * .1)`

which looks very odd to me. Can anyone explain me, why there is a 0.1 in? Seems like this samples only 10% of all data (or even less..)

Best,
Martin

**Comment by theanine** [comment]
I think you answered your own question.  It's simply a 10% sampling of the data, that's all.

**Comment by MartinLiebig** [comment]
thanks, i thought i oversaw something :)
